services:
  - type: web
    name: carrito-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    rootDir: server
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: carrito-db
          property: connectionString

  - type: web
    name: carrito-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: client
